### ISSUE TITLE
Can't Recieve   No address from wallet

### ISSUE THREAD

**Issue by kylexis** [NemProject/nem.core#14]
I have downloaded the NEM Wallet multiple times.... There is no value in the account since I haven't transferred any Nem to it....
3 Questions....
1  How do I get an address to transfer the NEM coins to my wallet?
2  How do I start Mining or using the Node... and 
3  When I use it... what is the benefit?
Thanks
Don Berdeaux

**Comment by alvin-reyes** [comment]
1. Go to one of the NEM faucets available and see if you can grab some XEMS for your account. 
2. Mining in NEM is harvesting and the only way you can start harvesting is if you have at least 10k XEM vested balance. Check out this guide for more info https://blog.nem.io/how-to-activate-start-delegated-harvesting-in-nanowallet/
3. NEM Wallet (NanoWallet) is used to store XEMs securely.

**Comment by gimer** [comment]
if problem is still valid report in proper wallet issue page not in nem.core
