### ISSUE TITLE
Bug in description: link is not working

### ISSUE THREAD

**Issue by Dmatafonov** [NemProject/nem.core#20]
![image](https://user-images.githubusercontent.com/8863854/34653959-9fe95fa2-f405-11e7-9c69-109b6e2ece20.png)

At this block:
https://nemproject.github.io/#requestPrepareAnnounce

BUG bounty: NDNRSW-FEQ256-HQLUYT-L6SOS3-RYHEJK-BLOWL2-C6MJ

**Comment by Dmatafonov** [comment]
Other two links dont work as well:

![image](https://user-images.githubusercontent.com/8863854/34658407-ec11d992-f43f-11e7-8bc0-cc8424b4b97b.png)

**Comment by gimer** [comment]
(in future please report in https://github.com/NemProject/NemProject.github.io/ )
