### ISSUE TITLE
why not open source totally?

### ISSUE THREAD

**Issue by williamzhang11** [NemProject/nem.core#21]

**Comment by williamzhang11** [comment]
Do your have some plan about it

**Comment by AencoCTO** [comment]
which part is not open source?

**Comment by cyberience** [comment]
What is not open? I understand that under the MIT all code that is part of the system that connects to or compiled with anything that is MIT must be open. So I am particularly interested in this project and winder what is not available before I start to dig in and suddenly find myself at a road block?

**Comment by gimer** [comment]
ask on forums or telegram
