### ISSUE TITLE
ProvisionNamespaceTransaction - Constructor with High Fees

### ISSUE THREAD

**Issue by denizdurmus** [NemProject/nem.core#23]
In org.nem.core.model.ProvisionNamespaceTransaction.java:

public ProvisionNamespaceTransaction(
            final TimeInstant timeStamp,
            final Account sender,
            final NamespaceIdPart newPart,
            final NamespaceId parent) {
        this(timeStamp, sender, MosaicConstants.NAMESPACE_OWNER_NEM, **null == parent ? Amount.fromNem(50_000) : Amount.fromNem(5_000)**, newPart, parent);
}

Above, the rental fee part is quite a lot, and based on nanowallet, only 100 needed for a new namespace w/o parent. The other constructor is ok for that purpose, but for beginners the above one is kinda confusing. Would that be better if a deprecated annotation is added, if not completely removing it?

**Comment by gimer** [comment]
IIRC this ctor is only used in tests (and could easily be found by looking for usages)
