### ISSUE TITLE
is possible get transaction hash from NIS or SDKs?

### ISSUE THREAD

**Issue by JokerCatz** [NemProject/nem.core#29]
is possible get transaction hash from NIS or SDKs?

I can't get transaction hash (like btc : txid or eth : txhash) without broadcast , & I can't get it from NIS API like `/block/at/public` too ( if I want get it without from my account or offline sign ) ... anybody can help me or use another SDKs (without the web explorer ... ) ?

**Comment by JokerCatz** [comment]
I found /local/* can be get it

**Comment by boy-good** [comment]
> 我发现/ local / *可以得到它

how to get hash？
