### ISSUE TITLE
How to get test coin ?

### ISSUE THREAD

**Issue by LmingXie** [NemProject/nem.core#44]
I can find the test network, but I can't get the test coin.Please transfer some test coins to this address:TDM7G4UBTUQWT7J45YZG4MCZKXKHTGY53PQIM7TG

**Comment by biscodyl** [comment]
http://faucet.testnet.symboldev.network/

**Comment by LmingXie** [comment]
> http://faucet.testnet.symboldev.network/

No, I need XEM test coin, not XYM

**Comment by gimer** [comment]
I doubt this is still actual, but please ask on discord
