### ISSUE TITLE
Request Support for BLS12 based signature verification

### ISSUE THREAD

**Issue by sudesh-supraoracles** [NemProject/nem.core#47]
Hi Team!

Since many protocols are putting BLS12 to use for digital signatures.
I want to verify BLS 12 based signature from the NEM smart contract.

Hoping for some positive inputs/response on this.

**Comment by gimre-xymcity** [comment]
Can you give us details, what kind of smart contract you'd want to deploy? (and actually how)

**Comment by gimre-xymcity** [comment]
[closed due to lack of activity]
