### ISSUE TITLE
tagged releases do not contain needed release information

### ISSUE THREAD

**Issue by jblanchette-circle** [NemProject/nem.core#59]
hi folks

we are ensuring that we keep up with all blockchain releases by watching official github tags and releases

nem.core at the moment is not adding any additional information to their tags and not utilizing the release feature which could deliver critical information about the release

the NEM hard fork is an example of when this information is "must-have"

**Comment by Jaguar0625** [comment]
This is the SDK repository. You should be looking at the NIS Client repository for such information: https://github.com/NemProject/nis/releases/tag/v0.6.98
